
List<Map<String,dynamic>>Brach_Sencess=[
  {
    'id':1,
    'title':'عربي',
    'image':'assest/images/img_6.png'
  },
  {
    'id':2,
    'title':'رياضيات',
    'image':'assest/images/img_2.png'
  },
  {
    'id':3,
    'title':'علوم',
    'image':'assest/images/img_3.png'
  },
  {
    'id':4,
    'title':'فرنسي',
    'image':'assest/images/img_4.png'
  },
  {
    'id':5,
    'title':'فيزياء',
    'image':'assest/images/img_7.png'
  },
  {
    'id':6,
    'title':'كيمياء',
    'image':'assest/images/img_8.png'
  },
  {
    'id':6,
    'title':'كيمياء',
    'image':'assest/images/img_8.png'
  },
  {
    'id':6,
    'title':'كيمياء',
    'image':'assest/images/img_8.png'
  }, {
    'id':6,
    'title':'كيمياء',
    'image':'assest/images/img_8.png'
  },
];


List<Map<String,dynamic>>Brach_Lib=[
{
  'id':1,
'title':'عربي',
'image':'assest/images/img_6.png'
},
{
  'id':2,
'title':'تاريخ',
'image':'assest/images/img_11.png'
},
{
  'id':3,
'title':'جغرافيا',
'image':'assest/images/img_12.png'
},
{
  'id':4,
'title':'فلسفة',
'image':'assest/images/img_10.png'
},
{
  'id':5,
'title':'انكليزي',
'image':'assest/images/img_9.png'
},
{
  'id':6,
'title':'فرنسي',
'image':'assest/images/img_4.png'
},];